// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"task_cli/core"
	"task_cli/infras"
)

// Injectors from wire.go:

func InitializeTaskUseCase(ctx context.Context) (core.TaskUseCases, error) {
	client, err := infras.NewClient()
	if err != nil {
		return core.TaskUseCases{}, err
	}
	taskRepository := infras.NewTaskRepository(client, ctx)
	taskUseCases := core.NewTaskUseCases(taskRepository)
	return taskUseCases, nil
}
